// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // Migrations run against the direct (unpooled) Neon connection string.
  // The app's runtime PrismaClient uses the pooled DATABASE_URL instead — see lib/prisma.ts.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
